"""
Amanflix Production Update Helper
==================================

Automates production version updates by swapping code folders while preserving
the virtual environment and data configuration.

Usage:
    python update_helper.py configure       - Set up paths interactively
    python update_helper.py update          - Perform a version update
    python update_helper.py update --dry-run - Show what update would do
    python update_helper.py status          - Show current config and system state
    python update_helper.py rollback        - Restore from a backup
    python update_helper.py clean           - Delete old backups

Expected folder structure:
    Z:\\Amanflix\\
    ├── Data\\                  (permanent data - uploads, posters, db, etc.)
    ├── Amanflix_prod\\         (current production code)
    ├── Amanflix_new_version\\  (downloaded new version)
    ├── Amanflix_backups\\      (archived old versions)
    ├── update_helper.py       (this script)
    └── update_config.json     (generated by 'configure')
"""

import os
import sys
import json
import shutil
import subprocess
import signal
import time
from datetime import datetime


SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
CONFIG_FILE = os.path.join(SCRIPT_DIR, 'update_config.json')


# ─── Helpers ─────────────────────────────────────────────────────────────────

def load_config():
    if not os.path.exists(CONFIG_FILE):
        print("[ERROR] update_config.json not found. Run 'python update_helper.py configure' first.")
        sys.exit(1)
    with open(CONFIG_FILE, 'r') as f:
        return json.load(f)


def save_config(config):
    with open(CONFIG_FILE, 'w') as f:
        json.dump(config, f, indent=4)
    print(f"[OK] Config saved to {CONFIG_FILE}")


def resolve_path(path):
    """Resolve a path relative to the script directory."""
    if os.path.isabs(path):
        return os.path.normpath(path)
    return os.path.normpath(os.path.join(SCRIPT_DIR, path))


def find_app_process():
    """Find running app.py process. Returns list of PIDs."""
    pids = []
    try:
        if sys.platform == 'win32':
            result = subprocess.run(
                ['wmic', 'process', 'where',
                 "commandline like '%app.py%' and name like '%python%'",
                 'get', 'processid'],
                capture_output=True, text=True, timeout=10
            )
            for line in result.stdout.strip().split('\n'):
                line = line.strip()
                if line.isdigit():
                    pids.append(int(line))
        else:
            result = subprocess.run(
                ['pgrep', '-f', 'app.py'],
                capture_output=True, text=True, timeout=10
            )
            for line in result.stdout.strip().split('\n'):
                line = line.strip()
                if line.isdigit():
                    pids.append(int(line))
    except Exception as e:
        print(f"[WARN] Could not check for running processes: {e}")
    return pids


def stop_app(config):
    """Stop the running app.py process."""
    pids = find_app_process()
    if not pids:
        print("[INFO] No running app.py process found.")
        return True

    print(f"[INFO] Found app.py process(es): {pids}")
    for pid in pids:
        try:
            if sys.platform == 'win32':
                subprocess.run(['taskkill', '/F', '/PID', str(pid)],
                             capture_output=True, timeout=10)
            else:
                os.kill(pid, signal.SIGTERM)
            print(f"[OK] Stopped process {pid}")
        except Exception as e:
            print(f"[WARN] Could not stop process {pid}: {e}")

    # Wait for processes to exit
    time.sleep(2)

    # Verify they stopped
    remaining = find_app_process()
    if remaining:
        print(f"[WARN] Some processes still running: {remaining}")
        return False
    print("[OK] All app.py processes stopped.")
    return True


def start_app(config):
    """Start app.py using the venv's Python interpreter."""
    prod_path = resolve_path(config['prod_folder'])
    api_path = os.path.join(prod_path, 'api')
    venv_rel = config.get('venv_path', 'api/venv')
    venv_path = os.path.join(prod_path, venv_rel)

    if sys.platform == 'win32':
        python_exe = os.path.join(venv_path, 'Scripts', 'python.exe')
    else:
        python_exe = os.path.join(venv_path, 'bin', 'python')

    if not os.path.exists(python_exe):
        print(f"[ERROR] Python executable not found at {python_exe}")
        print("[INFO] You may need to start the app manually.")
        return False

    app_py = os.path.join(api_path, 'app.py')
    if not os.path.exists(app_py):
        print(f"[ERROR] app.py not found at {app_py}")
        return False

    print(f"[INFO] Starting app.py from {api_path}")
    try:
        if sys.platform == 'win32':
            subprocess.Popen(
                [python_exe, 'app.py'],
                cwd=api_path,
                creationflags=subprocess.CREATE_NEW_PROCESS_GROUP | subprocess.DETACHED_PROCESS
            )
        else:
            subprocess.Popen(
                [python_exe, 'app.py'],
                cwd=api_path,
                start_new_session=True,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL
            )
        print("[OK] app.py started successfully.")
        return True
    except Exception as e:
        print(f"[ERROR] Failed to start app.py: {e}")
        return False


def generate_data_config(config):
    """Generate data_config.json content for the app."""
    return {
        "data_root": config['data_root_relative']
    }


# ─── Commands ────────────────────────────────────────────────────────────────

def cmd_configure():
    """Interactive configuration setup."""
    print("=" * 60)
    print("  Amanflix Update Helper - Configuration")
    print("=" * 60)
    print()

    config = {}

    # Data folder
    print("Enter the path to the Data folder (uploads, posters, db, etc.).")
    print("This can be absolute (Z:\\Amanflix\\Data) or relative to this script.")
    data_path = input("Data folder path [Data]: ").strip()
    if not data_path:
        data_path = 'Data'
    full_data = resolve_path(data_path)
    if not os.path.exists(full_data):
        print(f"[WARN] Path does not exist yet: {full_data}")
        create = input("Create it? (y/N): ").strip().lower()
        if create == 'y':
            os.makedirs(full_data, exist_ok=True)
            print(f"[OK] Created {full_data}")
        else:
            print("[INFO] Continuing without creating it.")
    config['data_folder'] = data_path

    # Production folder
    print()
    print("Enter the production folder name/path (e.g., 'Amanflix_prod').")
    prod_path = input("Production folder: ").strip()
    if not prod_path:
        prod_path = 'Amanflix_prod'
    full_prod = resolve_path(prod_path)
    if not os.path.exists(full_prod):
        print(f"[WARN] Production folder not found: {full_prod}")
        print(f"       Make sure the folder exists and is named '{os.path.basename(full_prod)}'.")
        print(f"       If it has a different name, rename it before running an update.")
    else:
        print(f"[OK] Production folder found: {full_prod}")
    config['prod_folder'] = prod_path

    # New version folder
    print()
    print("Enter the new version folder name/path (e.g., 'Amanflix_new_version').")
    new_path = input("New version folder: ").strip()
    if not new_path:
        new_path = 'Amanflix_new_version'
    config['new_version_folder'] = new_path

    # Backup folder
    print()
    print("Enter the backup folder name/path (e.g., 'Amanflix_backups').")
    backup_path = input("Backup folder: ").strip()
    if not backup_path:
        backup_path = 'Amanflix_backups'
    full_backup = resolve_path(backup_path)
    if not os.path.exists(full_backup):
        os.makedirs(full_backup, exist_ok=True)
        print(f"[OK] Created backup folder: {full_backup}")
    config['backup_folder'] = backup_path

    # Venv path (relative to prod folder)
    print()
    print("Enter the venv path relative to the production folder (default: api/venv).")
    venv_path = input("Venv path [api/venv]: ").strip()
    if not venv_path:
        venv_path = 'api/venv'
    config['venv_path'] = venv_path

    # Compute data_root relative path for data_config.json
    # From prod_folder/api/ to data_folder
    prod_api_full = os.path.join(resolve_path(prod_path), 'api')
    data_root_rel = os.path.relpath(full_data, prod_api_full)
    config['data_root_relative'] = data_root_rel

    print()
    print("─" * 60)
    print("  Configuration Summary")
    print("─" * 60)
    print(f"  Data folder:       {resolve_path(config['data_folder'])}")
    print(f"  Production folder: {resolve_path(config['prod_folder'])}")
    print(f"  New version:       {resolve_path(config['new_version_folder'])}")
    print(f"  Backup folder:     {resolve_path(config['backup_folder'])}")
    print(f"  Venv path:         {config['venv_path']}")
    print(f"  data_root (app):   {data_root_rel}")
    print("─" * 60)
    print()

    confirm = input("Save this configuration? (Y/n): ").strip().lower()
    if confirm == 'n':
        print("[INFO] Configuration not saved.")
        return

    save_config(config)

    # Also generate data_config.json for the app
    data_config = generate_data_config(config)
    prod_api = os.path.join(resolve_path(config['prod_folder']), 'api')
    if os.path.exists(prod_api):
        dc_path = os.path.join(prod_api, 'config', 'data_config.json')
        with open(dc_path, 'w') as f:
            json.dump(data_config, f, indent=4)
        print(f"[OK] data_config.json written to {dc_path}")
    else:
        print(f"[INFO] Production api/ folder not found at {prod_api}")
        print(f"[INFO] data_config.json will be generated during update.")

    print()
    print("[DONE] Configuration complete. Run 'python update_helper.py update' to perform an update.")


def cmd_update(dry_run=False):
    """Perform a production version update."""
    config = load_config()

    prod_path = resolve_path(config['prod_folder'])
    new_version_path = resolve_path(config['new_version_folder'])
    backup_folder = resolve_path(config['backup_folder'])
    venv_rel = config.get('venv_path', 'api/venv')

    print("=" * 60)
    if dry_run:
        print("  Amanflix Production Update (DRY RUN)")
    else:
        print("  Amanflix Production Update")
    print("=" * 60)
    print()

    # ── Validate ──────────────────────────────────────────────
    if not os.path.exists(new_version_path):
        print(f"[ERROR] New version folder not found: {new_version_path}")
        print("[INFO] Download the new version and place it at the expected path.")
        sys.exit(1)

    if not os.path.exists(prod_path):
        print(f"[ERROR] Production folder not found: {prod_path}")
        print(f"[INFO] Can't find the production folder. Please check that it exists")
        print(f"       and is named correctly (expected: {os.path.basename(prod_path)}).")
        print(f"       If the folder has a different name, rename it to '{os.path.basename(prod_path)}'.")
        sys.exit(1)

    # Check if new version already has a venv
    new_venv_path = os.path.join(new_version_path, venv_rel)
    restore_venv = True
    if os.path.exists(new_venv_path):
        print(f"[WARN] New version already contains a venv at: {new_venv_path}")
        if dry_run:
            print("  [DRY RUN] Would ask whether to delete or keep new venv.")
        else:
            choice = input("Delete it and restore the current venv? (y = delete & restore, n = keep new venv): ").strip().lower()
            if choice == 'y':
                shutil.rmtree(new_venv_path)
                print("  [OK] venv in new version deleted.")
            else:
                print("  [INFO] Will keep the new version's venv. Skipping venv transfer.")
                restore_venv = False

    # ── Confirm ───────────────────────────────────────────────
    print(f"  Current prod:    {prod_path}")
    print(f"  New version:     {new_version_path}")
    print(f"  Backup folder:   {backup_folder}")
    print()

    if dry_run:
        print("[DRY RUN] The following steps would be performed:")
        print("  1. Stop app.py")
        print("  2. Extract venv and data_config.json from current prod")
        print("  3. Archive current prod to backups")
        print("  4. Rename new version folder to prod")
        print("  5. Restore venv and data_config.json into new prod")
        print()
        print("[DRY RUN] No changes were made.")
        return

    confirm = input("Proceed with the update? (y/N): ").strip().lower()
    if confirm != 'y':
        print("[INFO] Update cancelled.")
        return

    timestamp = datetime.now().strftime('%Y-%m-%d_%H-%M-%S')

    # ── Step 1: Stop app ──────────────────────────────────────
    print()
    print("[Step 1/5] Stopping app.py...")
    stop_app(config)

    # ── Step 2: Extract venv + data_config from old prod ──────
    venv_temp_path = os.path.join(SCRIPT_DIR, '_venv_temp')
    data_config_content = None

    print("[Step 2/5] Extracting venv and data_config.json from current prod...")
    venv_src = os.path.join(prod_path, venv_rel)
    data_config_src = os.path.join(prod_path, 'api', 'config', 'data_config.json')

    # Extract venv (only if we need to restore it later)
    if restore_venv:
        if os.path.exists(venv_src):
            if os.path.exists(venv_temp_path):
                shutil.rmtree(venv_temp_path)
            print(f"  Moving venv to temp: {venv_temp_path}")
            shutil.move(venv_src, venv_temp_path)
            print("  [OK] venv extracted.")
        else:
            print(f"  [WARN] venv not found at {venv_src}")
    else:
        print("  [SKIP] venv transfer skipped (keeping new version's venv).")

    # Extract data_config.json content
    if os.path.exists(data_config_src):
        with open(data_config_src, 'r') as f:
            data_config_content = json.load(f)
        print("  [OK] data_config.json read.")
    else:
        print("  [INFO] No data_config.json found, will generate from update_config.")
        data_config_content = generate_data_config(config)

    # ── Step 3: Move old prod to backups ──────────────────────
    print("[Step 3/5] Archiving current production...")
    backup_name = f"backup_{timestamp}"
    backup_dest = os.path.join(backup_folder, backup_name)
    os.makedirs(backup_folder, exist_ok=True)
    print(f"  Moving {prod_path} -> {backup_dest}")
    shutil.move(prod_path, backup_dest)
    print(f"  [OK] Old prod archived as {backup_name}")

    # ── Step 4: Rename new version to prod ────────────────────
    print("[Step 4/5] Activating new version...")
    print(f"  Renaming {new_version_path} -> {prod_path}")
    shutil.move(new_version_path, prod_path)
    print("  [OK] New version is now production.")

    # ── Step 5: Restore venv + data_config ────────────────────
    print("[Step 5/5] Restoring venv and data_config.json...")

    # Restore venv
    venv_dest = os.path.join(prod_path, venv_rel)
    if restore_venv:
        if os.path.exists(venv_temp_path):
            # Remove any venv that came with the new version to avoid nesting
            if os.path.exists(venv_dest):
                shutil.rmtree(venv_dest)
            # Ensure parent directory exists
            venv_parent = os.path.dirname(venv_dest)
            os.makedirs(venv_parent, exist_ok=True)
            print(f"  Moving venv back: {venv_dest}")
            shutil.move(venv_temp_path, venv_dest)
            print("  [OK] venv restored.")
        else:
            print("  [WARN] No venv to restore. You may need to create one manually.")
    else:
        print("  [SKIP] venv restore skipped (using new version's venv).")

    # Write data_config.json
    data_config_dest = os.path.join(prod_path, 'api', 'config', 'data_config.json')
    if data_config_content:
        os.makedirs(os.path.dirname(data_config_dest), exist_ok=True)
        with open(data_config_dest, 'w') as f:
            json.dump(data_config_content, f, indent=4)
        print(f"  [OK] data_config.json written to {data_config_dest}")

    print()
    print("=" * 60)
    print(f"  Update complete! ({timestamp})")
    print("=" * 60)
    print()
    print("[INFO] App was NOT started automatically.")
    print("[INFO] Start it manually when you're ready.")


def cmd_status():
    """Show current configuration and system state."""
    config = load_config()

    print("=" * 60)
    print("  Amanflix Update Helper - Status")
    print("=" * 60)
    print()

    # Show config
    print("Configuration:")
    print(f"  Data folder:       {resolve_path(config['data_folder'])}")
    print(f"  Production folder: {resolve_path(config['prod_folder'])}")
    print(f"  New version:       {resolve_path(config['new_version_folder'])}")
    print(f"  Backup folder:     {resolve_path(config['backup_folder'])}")
    print(f"  Venv path:         {config.get('venv_path', 'api/venv')}")
    print(f"  data_root (app):   {config.get('data_root_relative', 'N/A')}")
    print()
    print()

    # Check paths
    print("Path Validation:")
    paths_to_check = {
        'Data folder': resolve_path(config['data_folder']),
        'Production folder': resolve_path(config['prod_folder']),
        'Backup folder': resolve_path(config['backup_folder']),
    }

    data_subdirs = ['uploads', 'posters_combined', 'files', 'instance', 'backups', 'logs']
    for sub in data_subdirs:
        paths_to_check[f'  Data/{sub}'] = os.path.join(resolve_path(config['data_folder']), sub)

    # Check venv
    prod = resolve_path(config['prod_folder'])
    venv_rel = config.get('venv_path', 'api/venv')
    paths_to_check['  Venv'] = os.path.join(prod, venv_rel)
    paths_to_check['  app.py'] = os.path.join(prod, 'api', 'app.py')
    paths_to_check['  data_config.json'] = os.path.join(prod, 'api', 'config', 'data_config.json')

    # New version check
    new_version = resolve_path(config['new_version_folder'])
    new_exists = os.path.exists(new_version)

    all_ok = True
    for label, path in paths_to_check.items():
        exists = os.path.exists(path)
        status = "[OK]  " if exists else "[MISS]"
        if not exists:
            all_ok = False
        print(f"  {status} {label}: {path}")

    print(f"  {'[OK]  ' if new_exists else '[----]'} New version folder: {new_version}")
    if new_exists:
        print(f"         --> New version detected! Run 'python update_helper.py update' to update.")
    else:
        print(f"         (No new version waiting - this is normal)")
    print()

    # Check running process
    print("App Process:")
    pids = find_app_process()
    if pids:
        print(f"  [RUNNING] app.py is running (PID: {', '.join(map(str, pids))})")
    else:
        print(f"  [STOPPED] app.py is not running")
    print()

    # List backups
    backup_folder = resolve_path(config['backup_folder'])
    if os.path.exists(backup_folder):
        backups = sorted([d for d in os.listdir(backup_folder)
                         if os.path.isdir(os.path.join(backup_folder, d))],
                        reverse=True)
        print(f"Available Backups ({len(backups)}):")
        if backups:
            for b in backups[:10]:
                size = _get_dir_size_str(os.path.join(backup_folder, b))
                print(f"  - {b} ({size})")
            if len(backups) > 10:
                print(f"  ... and {len(backups) - 10} more")
        else:
            print("  (none)")
    print()

    if all_ok:
        print("[OK] All paths valid. System looks good.")
    else:
        print("[WARN] Some paths are missing. Check the output above.")


def _get_dir_size_str(path):
    """Get a human-readable size estimate for a directory (fast, top-level only)."""
    try:
        total = 0
        for entry in os.scandir(path):
            if entry.is_file(follow_symlinks=False):
                total += entry.stat().st_size
            elif entry.is_dir(follow_symlinks=False):
                # Just count top level for speed
                total += 4096
        if total > 1024 * 1024 * 1024:
            return f"{total / (1024**3):.1f} GB"
        elif total > 1024 * 1024:
            return f"{total / (1024**2):.1f} MB"
        else:
            return f"{total / 1024:.0f} KB"
    except Exception:
        return "unknown size"


def cmd_rollback():
    """Restore from a backup."""
    config = load_config()

    backup_folder = resolve_path(config['backup_folder'])
    prod_path = resolve_path(config['prod_folder'])
    venv_rel = config.get('venv_path', 'api/venv')

    if not os.path.exists(backup_folder):
        print("[ERROR] Backup folder not found.")
        sys.exit(1)

    # List backups
    backups = sorted([d for d in os.listdir(backup_folder)
                     if os.path.isdir(os.path.join(backup_folder, d))],
                    reverse=True)

    if not backups:
        print("[ERROR] No backups available.")
        sys.exit(1)

    print("=" * 60)
    print("  Amanflix Rollback")
    print("=" * 60)
    print()
    print("Available backups:")
    for i, b in enumerate(backups):
        print(f"  {i + 1}. {b}")

    print()
    choice = input(f"Select backup to restore (1-{len(backups)}) or 'q' to cancel: ").strip()
    if choice.lower() == 'q':
        print("[INFO] Rollback cancelled.")
        return

    try:
        idx = int(choice) - 1
        if idx < 0 or idx >= len(backups):
            raise ValueError
    except ValueError:
        print("[ERROR] Invalid selection.")
        return

    selected_backup = backups[idx]
    backup_path = os.path.join(backup_folder, selected_backup)

    print()
    print(f"Will restore: {selected_backup}")
    print(f"Current prod will be archived as a new backup.")
    confirm = input("Proceed? (y/N): ").strip().lower()
    if confirm != 'y':
        print("[INFO] Rollback cancelled.")
        return

    timestamp = datetime.now().strftime('%Y-%m-%d_%H-%M-%S')

    # Stop app
    print()
    print("[Step 1/5] Stopping app.py...")
    stop_app(config)

    # Extract venv from current prod
    venv_temp_path = os.path.join(SCRIPT_DIR, '_venv_temp')
    data_config_content = None

    if os.path.exists(prod_path):
        print("[Step 2/5] Extracting venv from current prod...")
        venv_src = os.path.join(prod_path, venv_rel)
        data_config_src = os.path.join(prod_path, 'api', 'config', 'data_config.json')

        if os.path.exists(venv_src):
            if os.path.exists(venv_temp_path):
                shutil.rmtree(venv_temp_path)
            shutil.move(venv_src, venv_temp_path)
            print("  [OK] venv extracted.")

        if os.path.exists(data_config_src):
            with open(data_config_src, 'r') as f:
                data_config_content = json.load(f)
            print("  [OK] data_config.json read.")
        else:
            data_config_content = generate_data_config(config)

        # Archive current prod
        print("[Step 3/5] Archiving current prod before rollback...")
        rollback_backup_name = f"pre_rollback_{timestamp}"
        rollback_backup_dest = os.path.join(backup_folder, rollback_backup_name)
        shutil.move(prod_path, rollback_backup_dest)
        print(f"  [OK] Current prod archived as {rollback_backup_name}")
    else:
        print("[Step 2/5] No current prod to extract from.")
        print("[Step 3/5] No current prod to archive.")
        data_config_content = generate_data_config(config)

    # Restore selected backup to prod
    print("[Step 4/5] Restoring backup to production...")
    shutil.copytree(backup_path, prod_path)
    print(f"  [OK] {selected_backup} restored as production.")

    # Restore venv + data_config
    print("[Step 5/5] Restoring venv and data_config.json...")
    venv_dest = os.path.join(prod_path, venv_rel)
    if os.path.exists(venv_temp_path):
        # Remove any venv that came from the backup
        if os.path.exists(venv_dest):
            shutil.rmtree(venv_dest)
        venv_parent = os.path.dirname(venv_dest)
        os.makedirs(venv_parent, exist_ok=True)
        shutil.move(venv_temp_path, venv_dest)
        print("  [OK] venv restored.")

    data_config_dest = os.path.join(prod_path, 'api', 'config', 'data_config.json')
    if data_config_content:
        os.makedirs(os.path.dirname(data_config_dest), exist_ok=True)
        with open(data_config_dest, 'w') as f:
            json.dump(data_config_content, f, indent=4)
        print("  [OK] data_config.json written.")

    # Start app
    start_app(config)

    print()
    print("=" * 60)
    print(f"  Rollback complete! Restored: {selected_backup}")
    print("=" * 60)


def cmd_clean():
    """Delete old backups, keeping the most recent N."""
    config = load_config()
    backup_folder = resolve_path(config['backup_folder'])

    if not os.path.exists(backup_folder):
        print("[ERROR] Backup folder not found.")
        sys.exit(1)

    backups = sorted([d for d in os.listdir(backup_folder)
                     if os.path.isdir(os.path.join(backup_folder, d))],
                    reverse=True)

    if not backups:
        print("[INFO] No backups to clean.")
        return

    print("=" * 60)
    print("  Amanflix Backup Cleanup")
    print("=" * 60)
    print()
    print(f"Found {len(backups)} backup(s):")
    for i, b in enumerate(backups):
        size = _get_dir_size_str(os.path.join(backup_folder, b))
        print(f"  {i + 1}. {b} ({size})")
    print()

    keep_input = input("How many recent backups to keep? [3]: ").strip()
    if not keep_input:
        keep_count = 3
    else:
        try:
            keep_count = int(keep_input)
            if keep_count < 0:
                raise ValueError
        except ValueError:
            print("[ERROR] Invalid number.")
            return

    to_delete = backups[keep_count:]
    if not to_delete:
        print(f"[INFO] Nothing to delete. You have {len(backups)} backup(s), keeping {keep_count}.")
        return

    print()
    print(f"Will DELETE {len(to_delete)} backup(s):")
    for b in to_delete:
        print(f"  - {b}")
    print(f"Will KEEP {min(keep_count, len(backups))} most recent backup(s).")
    print()

    confirm = input("Proceed with deletion? (y/N): ").strip().lower()
    if confirm != 'y':
        print("[INFO] Cleanup cancelled.")
        return

    deleted = 0
    for b in to_delete:
        path = os.path.join(backup_folder, b)
        try:
            shutil.rmtree(path)
            print(f"  [OK] Deleted {b}")
            deleted += 1
        except Exception as e:
            print(f"  [ERROR] Failed to delete {b}: {e}")

    print()
    print(f"[DONE] Deleted {deleted} backup(s). {min(keep_count, len(backups))} remaining.")


# ─── Main ────────────────────────────────────────────────────────────────────

def main():
    if len(sys.argv) < 2:
        print("Amanflix Update Helper")
        print()
        print("Usage:")
        print("  python update_helper.py configure       - Set up paths interactively")
        print("  python update_helper.py update          - Perform a version update")
        print("  python update_helper.py update --dry-run - Show what update would do")
        print("  python update_helper.py status          - Show current config and state")
        print("  python update_helper.py rollback        - Restore from a backup")
        print("  python update_helper.py clean           - Delete old backups")
        sys.exit(0)

    command = sys.argv[1].lower()

    if command == 'configure':
        cmd_configure()
    elif command == 'update':
        dry_run = '--dry-run' in sys.argv[2:]
        cmd_update(dry_run=dry_run)
    elif command == 'status':
        cmd_status()
    elif command == 'rollback':
        cmd_rollback()
    elif command == 'clean':
        cmd_clean()
    else:
        print(f"[ERROR] Unknown command: {command}")
        print("Valid commands: configure, update, status, rollback, clean")
        sys.exit(1)


if __name__ == '__main__':
    main()
